server:
  port: 8080
  # servlet:
  #   context-path: /
  ssl:
    enabled: false


## logging
logging:
  file: /tmp/logs/app.log
  level:
    root: INFO
    com.supwisdom.institute.authx.demo.cas: DEBUG


## CAS

#应用地址
app.server.url: http://localhost:8080

#CAS服务地址
cas.server.url: https://cas.dev2.supwisdom.com/cas

